name: Continuous integration
on:
  pull_request:

jobs:
  syntax-check:
    name: Check syntax
    runs-on: ubuntu-latest
    container: python:3.11-slim
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Syntax check
        run: |
          . venv/bin/activate
          rstcheck --recursive --ignore-directives "tabs" source/
  build-error-check:
    name: Check build error
    runs-on: ubuntu-latest
    container: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create virtual environment
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
      - name: Build documentation
        run: |
          . venv/bin/activate
          sphinx-build -W -j 1 -a -D language='en' -b html source __preview
